backend:
  name: git-gateway
  repo: romerocs/wishlist
  branch: main # Branch to update (optional; defaults to master)
  # This line should *not* be indented
media_folder: "/public" # Media files will be stored in the repo under images/uploads
public_folder: "/" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://wishlist-cromero.netlify.app
collections:
  - name: "list" # Used in routes, e.g., /admin/collections/blog
    label: "List" # Used in the UI
    folder: "/src/data/list" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: lists/{{slug}}
    fields: # The fields for each document, usually in front matter
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "List Item"
        name: "list-item"
        widget: "list"
        fields: 
          - label: Title
            name: title
          - label: "URL"
            name: url
            required: false
          - label: "Price"
            name: price
            required: false
          - label: "Notes"
            name: notes
            required: false
            widget: "text"
          - label: "Priority"
            name: priority
            widget: "select"
            default:  "Medium"
            options: [{ label: "Low", value: "Low" }, { label: "Medium", value: "Medium" }, { label: "High", value: "High" }]
          - label: "Needs"
            name: needs
            widget: "number"
            default: 1
            value_type: "int"
            min: 1
            max: 100
          - label: "Has"
            name: has
            widget: "number"
            default: 0
            value_type: "int"
            min: 0
          - label: "Index"
            name: index
            widget: "hidden"
            value_type: "int"
            default: 0